version: '3'
services:
  api:
    build: app
    expose:
      - 80
    volumes:
      - ./app:/var/www/app
    command: "run uvicorn main:app --host 0.0.0.0 --port 80"
  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static:/usr/share/nginx/html/
